audit:
  kafka:
    topic: url-shortener-event-topic
    consumer:
      group-id: url-events-consumer

spring:
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092

  data:
    mongodb:
      uri: mongodb://localhost:27017/auditdatabase
      mapping:
        strict: false