audit:
  kafka:
    topic: ${AUDIT_KAFKA_TOPIC}
    consumer:
      group-id: ${AUDIT_KAFKA_GROUP_ID}

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      mapping:
        strict: ${SPRING_DATA_MONGODB_MAPPING_STRICT}